name: picture_picker
description: Flutter native selector works with android and ios.
version: 1.0.0
author: wayaer <wayaer@foxmail.com>
homepage: https://github.com/Wayaer/picture_picker
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: picture.picker
        pluginClass: PicturePickerPlugin
      ios:
        pluginClass: PicturePickerPlugin

