name: picture_picker
description: A new Flutter plugin about Picture Picker.
version: 0.0.1
author:  Wayaer
homepage: https://github.com/Wayaer/picture_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.picker.picture_picker
    pluginClass: PicturePickerPlugin
