name: picture_picker
description: A new Flutter plugin about Picture Picker.
version: 0.0.4
author: Wayaer <wayaer@foxmail.com>
homepage: https://github.com/Wayaer/picture_picker
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: picture.picker
        pluginClass: PicturePickerPlugin
      ios:
        pluginClass: PicturePickerPlugin

